encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>/", views.pages, name="pages"),
    path("search/", views.search, name="search"),
    path("add/", views.add, name="add")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django import forms
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from markdown2 import Markdown
from . import util

# markdown converter
markdowner = Markdown()

# form to add new entry
class AddForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea)
    title = forms.CharField(label="Save as: ")

# homepage to display links to all entries
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def pages(request, entry):

    # if entry is not listed in the entries then render a page not found
    all_entries = util.list_entries()
    if entry not in all_entries:
        return render(request, "encyclopedia/not_found.html")
    
    # convert md to html and save into a variable
    text = markdowner.convert(util.get_entry(entry))

    # render html page using the converted html and entry as a title
    return render(request, "encyclopedia/pages.html", {
        "data" : text,
        "entry" : entry
    })


def search(request):

    # get the query entered and the available pages
    query = request.POST.get("q")
    all_entries = util.list_entries()

    # make a list of substrings that matched the entries
    matches = []

    # if there is no direct match, check for substrings andd add the entries to Match list
    if query not in all_entries:
        for each in all_entries:
            if query in each:
                matches.append(each)
        return render(request, "encyclopedia/search.html", {
            "matches" : matches,
            "query" : query
        })
    else:
        # if query matches an entry, redirect to that page
        return HttpResponseRedirect(reverse("wiki:pages", kwargs={'entry': query}))
    

def add(request):
    if request.method == "POST":

        # create a new django form
        form = AddForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]

            # show error if entry already exists
            if title in util.list_entries():
                return render(request, "encyclopedia/exists.html")
            
            # save entry and redirect to the new page
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("wiki:pages", kwargs={'entry': title}))
        
    
    return render(request, "encyclopedia/new.html", {
        "form" : AddForm()
    })

def edit(request):
    # if method is post, save, else get pages name and render edit page with content already in the form
    if request.method == "POST":
        re

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:add' %}"> Create New Page</a>
                </div>
                <div>
                    Random Page
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Add a new entry
{% endblock %}

{% block body %}
    <h2>Add a new entry</h2>
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/not_found.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia | Not found
{% endblock %}

{% block body %}
   <h1>Error 404</h1>
   <p>Sorry, but the page you were looking for is not found</p>
{% endblock %} 

encyclopedia/templates/encyclopedia/pages.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia | {{ entry }}
{% endblock %}

{% block body %}
    <form action="{% url 'wiki:add' %}" method="post">
        <textarea value=""
    </form>
   {{ data|safe }}
{% endblock %} 

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia | Not found
{% endblock %}

{% block body %}
    <h3>Searched: {{ query }}</h3>
    <ul>
    {% for each in matches %}

        <li><a href="{% url 'wiki:pages' entry=each %}">{{ each }}</a></li>

    {% endfor %}
    </ul>

{% endblock %} 